# Generated by Django 4.2.14 on 2024-07-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Brazo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Bluetooth',
        ),
        migrations.DeleteModel(
            name='BrazoRobotico',
        ),
        migrations.RemoveField(
            model_name='roboticarmaction',
            name='residue',
        ),
        migrations.RemoveField(
            model_name='roboticarmaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='SensorPeso',
        ),
        migrations.RemoveField(
            model_name='sistemarecoleccion',
            name='registro_residuos',
        ),
        migrations.RenameField(
            model_name='controlremoto',
            old_name='estado_conexion',
            new_name='estado_conexionBluetooth',
        ),
        migrations.RemoveField(
            model_name='controlremoto',
            name='interfaz_usuario',
        ),
        migrations.AddField(
            model_name='controlremoto',
            name='estado_conexionWifi',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Residue',
        ),
        migrations.DeleteModel(
            name='RoboticArmAction',
        ),
        migrations.DeleteModel(
            name='SistemaRecoleccion',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
