# Generated by Django 4.2.14 on 2024-07-29 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Brazo', '0002_weightdata_delete_bluetooth_delete_brazorobotico_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeightData',
        ),
    ]
